apiVersion: batch/v1
kind: Job
metadata:
  name: nasa-image-job
spec:
  template:
    spec:
      containers:
      - name: nasa-script
        image: your-dockerhub-user/nasa-script:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 3
