apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nasa-query-role-binding
  namespace: default
  labels:
    app: nasa-query
subjects:
  - kind: ServiceAccount
    name: nasa-query-sa
    namespace: default
roleRef:
  kind: Role
  name: nasa-query-role
  apiGroup: rbac.authorization.k8s.io
