apiVersion: v1
kind: PersistentVolume
metadata:
  name: nasa-data-pv
  labels:
    app: nasa-query
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
