apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nasa-data-pvc
  namespace: nasa-query-ns
  labels:
    app: nasa-query
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nasa-data-pv
  storageClassName: local-path