apiVersion: batch/v1
kind: Job
metadata:
  name: nasa-image-job
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: nasa-data
        persistentVolumeClaim:
          claimName: nasa-data-pvc
      containers:
      - name: nasa-script
        image: your-dockerhub-user/nasa-image-query:latest
        volumeMounts:
        - mountPath: /data
          name: nasa-data
        command: ["python", "/app/nasa_script.py"]